### ISSUE TITLE
The description is wrong

### ISSUE THREAD

**Issue by nco2k** [Ellivers/Why-Am-I-on-Fire#11]
> Warning display: You can choose between either: "Flash", which has the fire overlay flash twice a second, "Transparent", which displays a transparent fire overlay instead, or **"None", which always displays the overlay without any warning**.

should be:
> "None", which never displays the overlay.

**Comment by Ellivers** [comment]
"None" means that there is no warning, and the vanilla fire overlay is always displayed, essentially disabling the mod.

**Comment by Ellivers** [comment]
Oops wait, you're right.
