### ISSUE TITLE
I translated the add-on into Russian

### ISSUE THREAD

**Issue by Loker541** [Ellivers/Why-Am-I-on-Fire#13]
I translated the add-on into Russian, how do I enable it? If I replace the en_us.mcfunction file, nothing happens.

**Comment by Ellivers** [comment]
This is not the right repository for WorldTool questions. I have responded to you on the Discord server.

> Translating the plugin just means changing the few strings that the plugin contains (I assume you mean the biome plugin). Since you're using a plugin with a language that WorldTool doesn't support, you can replace the lang file like you did, then enable `Reload` in the [language settings](https://ellivers.github.io/worldtool-docs/docs/configuration#language).
