### ISSUE TITLE
Flash Config

### ISSUE THREAD

**Issue by Julienraptor01** [Ellivers/Why-Am-I-on-Fire#3]
The biggest problem with this mod for me is that :
> Why Am I on Fire works for both the client and server. For the best experience, use it on both sides.

> On client: Hides the fire overlay when the player either has fire resistance or is in creative mode. If the player is still on fire and either the fire resistance effect is about to wear off or they're holding a bucket of milk, the fire overlay will __***flash***__ as a warning.

Could you add an option similar to other minecraft accessibility options for the flashing ?

**Comment by Ellivers** [comment]
The flash was only every half second, not all that jarring, but a config option has been added to display the overlay partially transparent instead.
