### ISSUE TITLE
1.19 support :)

### ISSUE THREAD

**Issue by RaptaG** [Ellivers/Why-Am-I-on-Fire#4]

**Comment by Redd56** [comment]
:)

**Comment by Scarlaid** [comment]
+1

**Comment by RaptaG** [comment]
@Ellivers ?

**Comment by Scarlaid** [comment]
hello I just tried to ran this on 1.19.2 and it worked fine
add 1.19.2 tag on curseforge should be good
![image](https://user-images.githubusercontent.com/90851437/202851974-accdfd84-7750-46b0-833a-8c39c02ebb4c.png)

**Comment by Ellivers** [comment]
The mod is now updated to 1.19.2, since the config library required that anyway.
