### ISSUE TITLE
Botania compat?

### ISSUE THREAD

**Issue by anoomolu** [Ellivers/Why-Am-I-on-Fire#7]
Hiya, really neat little mod <3

I was wondering if you'd be willing to add mod compat for Botania? The Ring of Odin (botania:odin_ring) and Crimson Pendant (botania:super_lava_pendant) both confer lava immunity, but the fire overlay still shows up with this mod installed. I understand if you don't want to complicate the mod any further, just thought it might be nice ^^

**Comment by Ellivers** [comment]
Why was this closed?
